/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClusterTabComponent.java
 *
 * Created on 27-Sep-2010, 15:45:51
 */
package vortex.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JTabbedPane;

/**
 *
 * @author Nikolay
 */
public class ClusterTabComponent extends javax.swing.JPanel {

    /**
     * Creates new form ClusterTabComponent
     *
     * @param caption - a title of the tab
     */
    public ClusterTabComponent(String caption) {
        initComponents();
        txtCaption.setText(caption);
    }
    private ArrayList<ActionListener> alAL = new ArrayList<>();

    public void addCloseActionListener(ActionListener listener) {
        alAL.add(listener);
    }

    public void removeCloseActionListener(ActionListener listener) {
        alAL.remove(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtCaption = new javax.swing.JLabel();
        labelIco = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        txtCaption.setText("caption");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(txtCaption, gridBagConstraints);

        labelIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close_small.png"))); // NOI18N
        labelIco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelIcoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelIcoMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelIcoMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(labelIco, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    private final ImageIcon icoHL = new javax.swing.ImageIcon(getClass().getResource("/Close_HL_small.png"));
    private final ImageIcon ico = new javax.swing.ImageIcon(getClass().getResource("/Close_small.png"));
    private void labelIcoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIcoMouseEntered
        labelIco.setIcon(icoHL);
    }//GEN-LAST:event_labelIcoMouseEntered

    private void labelIcoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIcoMouseExited
        labelIco.setIcon(ico);
    }//GEN-LAST:event_labelIcoMouseExited

    private void labelIcoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIcoMouseReleased
        if (getParent() != null) {
            if (JTabbedPane.class.isAssignableFrom(getParent().getParent().getClass())) {
                JTabbedPane pane = (JTabbedPane) getParent().getParent();
                for (int i = 0; i < pane.getTabCount(); i++) {
                    if (pane.getTabComponentAt(i) == this) {
                        pane.remove(i);
                        fireCloseActionPerformed();
                    }
                }

            }
        }
    }//GEN-LAST:event_labelIcoMouseReleased

    private void fireCloseActionPerformed() {
        for (ActionListener actionListener : alAL) {
            actionListener.actionPerformed(new ActionEvent(this, 1, "Close tab"));
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelIco;
    private javax.swing.JLabel txtCaption;
    // End of variables declaration//GEN-END:variables
}
