/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmEnrichment.java
 *
 * Created on 16-Dec-2009, 13:15:52
 */
package vortex.gui;

import java.util.ArrayList;
import java.util.List;
import java.util.Map.Entry;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import samusik.glasscmp.GlassFrame;
import clustering.Cluster;
import clustering.ClusterSet;
import clustering.Datapoint;
import clustering.DistanceMatrix;
import clustering.DistanceMeasure;
import util.DefaultEntry;
import util.NormalStatistics;
import util.logger;

/**
 *
 * @author Nikolay
 */
public class frmPairwiseDistanceStat extends GlassFrame {

    private static final long serialVersionUID = 1L;
    private ValidationComputer computer;
    private ClusterSet css;

    /**
     * Creates new form frmEnrichment
     */
    @SuppressWarnings("unchecked")
    public frmPairwiseDistanceStat(ClusterSet css) {
        initComponents();
        Class[] c = DistanceMeasure.getAvailableSubclasses();
        for (Class c1 : c) {
            ((DefaultComboBoxModel) cmbDistanceMeasure.getModel()).addElement(new vortex.util.ClassWrapper(c1));
        }

        this.css = css;
    }

    /*TODO
     * - adding annotations to the list
     * - computing annotations for selected clusters
     * - call insurance
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        cmdComputeRatios = new samusik.glasscmp.GlassButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbDistanceMeasure = new samusik.glasscmp.GlassComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pairwise Distance Statistics");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(getBackground());
        jPanel1.setLayout(new java.awt.GridBagLayout());

        cmdComputeRatios.setText("Compute");
        cmdComputeRatios.setMaximumSize(new java.awt.Dimension(100, 28));
        cmdComputeRatios.setMinimumSize(new java.awt.Dimension(100, 28));
        cmdComputeRatios.setPreferredSize(new java.awt.Dimension(100, 28));
        cmdComputeRatios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdComputeRatiosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmdComputeRatios, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cluster", "Average Distance", "SD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        cmbDistanceMeasure.setMinimumSize(new java.awt.Dimension(34, 28));
        cmbDistanceMeasure.setPreferredSize(new java.awt.Dimension(34, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(cmbDistanceMeasure, gridBagConstraints);

        jLabel1.setText("Distance measure:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdComputeRatiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdComputeRatiosActionPerformed
        try {
            Class<? extends DistanceMeasure> c = ((vortex.util.ClassWrapper) cmbDistanceMeasure.getSelectedItem()).item;

            DistanceMeasure dm = c.getConstructor().newInstance();

            if (computer != null) {
                computer.cancel(true);
            }

            cmdComputeRatios.setText("Computing...");
            cmdComputeRatios.setEnabled(false);

            dm.init(css.getDataset());

            DefaultTableModel dtm = ((DefaultTableModel) jTable1.getModel());

            int rowCnt = dtm.getRowCount();
            for (int i = 0; i < rowCnt; i++) {
                dtm.removeRow(i);
            }

            DistanceMatrix dmtx = new DistanceMatrix(css.getDataset(), dm);

            for (Cluster clus : css.getClusters()) {
                Datapoint[] dp = new Datapoint[clus.size()];
                for (int i = 0; i < clus.getClusterMembers().length; i++) {
                    dp[i] = clus.getClusterMembers()[i].getDatapoint();
                }
                computer = new ValidationComputer(clus.toString(), dp, dtm, dmtx, false);
                computer.execute();
            }
            //logger.print("Total dataset:");
            computer = new ValidationComputer("Total dataset", css.getDataset().getDatapoints(), dtm, dmtx, false);
            computer.execute();


        } catch (Exception e) {
            logger.showException(e);
        }
    }//GEN-LAST:event_cmdComputeRatiosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (computer != null) {
            computer.cancel(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private class ValidationComputer extends SwingWorker<DefaultTableModel, Entry<String, NormalStatistics>> {

        private Datapoint[] dp;
        private DefaultTableModel dtm;
        private DistanceMatrix mtx;
        private String title;
        private boolean print = false;

        @Override
        protected void done() {
            mtx = null;
        }

        public ValidationComputer(String title, Datapoint[] dp, DefaultTableModel dtm, DistanceMatrix mtx, boolean print) {
            this.title = title;
            this.dp = dp;
            this.dtm = dtm;
            this.mtx = mtx;
            this.print = print;
        }

        @Override
        protected DefaultTableModel doInBackground() throws Exception {

            ArrayList<Double> al = new ArrayList<Double>();
            for (int i = 0; i < dp.length; i++) {
                for (int j = i + 1; j < dp.length; j++) {

                    if (print & (Math.random() < 0.005)) {
                        logger.print(mtx.getValue(dp[i], dp[j]));
                    }

                    al.add(mtx.getValue(dp[i], dp[j]));
                }
            }
            NormalStatistics ns = new NormalStatistics(al);
            publish(new DefaultEntry[]{new DefaultEntry(title, ns)});
            cmdComputeRatios.setText("Compute");
            cmdComputeRatios.setEnabled(true);
            return dtm;
        }

        @Override
        protected void process(List<Entry<String, NormalStatistics>> chunks) {
            for (Entry<String, NormalStatistics> m : chunks) {
                dtm.addRow(new Object[]{m.getKey(), m.getValue().getMean(), m.getValue().getSD()});
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private samusik.glasscmp.GlassComboBox cmbDistanceMeasure;
    private samusik.glasscmp.GlassButton cmdComputeRatios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
