/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * panAnnotationsBrowser.java
 *
 * Created on 24-Apr-2012, 22:16:35
 */
package vortex.gui;

import java.awt.Dimension;
import java.io.File;
import java.io.FileInputStream;
import java.util.AbstractMap.SimpleEntry;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.Map.Entry;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import clustering.Datapoint;
import clustering.Dataset;
import annotations.Annotation;
import java.util.List;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
import util.IO;
import util.logger;

/**
 *
 * @author Nikolay
 */
@SuppressWarnings("serial")
public class panAnnotationsBrowser extends javax.swing.JPanel {

    Dataset dataset;
    DefaultTableModel dtm;

    /**
     * Creates new form panAnnotationsBrowser
     */
    public panAnnotationsBrowser(Dataset nd) {
        initComponents();
        this.dataset = nd;
        for (Annotation a : nd.getAnnotations()) {
            cmbAnnotations.addItem(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        toolbar = new samusik.glasscmp.GlassToolBar();
        cmdDeleteAnnotation = new samusik.glasscmp.GlassButton();
        cmbAnnotations = new samusik.glasscmp.GlassComboBox();
        cmdDeleteAnnotation2 = new samusik.glasscmp.GlassButton();
        cmdImport = new samusik.glasscmp.GlassButton();
        scrollPane = new javax.swing.JScrollPane();
        tabAnnotationContents = new javax.swing.JTable();

        setLayout(new java.awt.GridBagLayout());

        toolbar.setMinimumSize(new java.awt.Dimension(80, 50));
        toolbar.setPreferredSize(new java.awt.Dimension(80, 50));
        toolbar.setLayout(new java.awt.GridBagLayout());

        cmdDeleteAnnotation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        cmdDeleteAnnotation.setToolTipText("Delete this annotation");
        cmdDeleteAnnotation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdDeleteAnnotation.setIconTextGap(0);
        cmdDeleteAnnotation.setMargin(new java.awt.Insets(2, 2, 2, 2));
        cmdDeleteAnnotation.setMaximumSize(new java.awt.Dimension(32, 32));
        cmdDeleteAnnotation.setMinimumSize(new java.awt.Dimension(32, 32));
        cmdDeleteAnnotation.setPreferredSize(new java.awt.Dimension(32, 32));
        cmdDeleteAnnotation.setVerifyInputWhenFocusTarget(false);
        cmdDeleteAnnotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteAnnotationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        toolbar.add(cmdDeleteAnnotation, gridBagConstraints);

        cmbAnnotations.setToolTipText("Select annotation");
        cmbAnnotations.setMaximumSize(new java.awt.Dimension(3000, 30));
        cmbAnnotations.setMinimumSize(new java.awt.Dimension(30, 30));
        cmbAnnotations.setPreferredSize(new java.awt.Dimension(30, 32));
        cmbAnnotations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAnnotationsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        toolbar.add(cmbAnnotations, gridBagConstraints);

        cmdDeleteAnnotation2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gear_32.png"))); // NOI18N
        cmdDeleteAnnotation2.setToolTipText("Merge/rename terms");
        cmdDeleteAnnotation2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdDeleteAnnotation2.setIconTextGap(0);
        cmdDeleteAnnotation2.setLabel(" Merge/rename terms");
        cmdDeleteAnnotation2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        cmdDeleteAnnotation2.setMaximumSize(new java.awt.Dimension(320, 32));
        cmdDeleteAnnotation2.setMinimumSize(new java.awt.Dimension(32, 32));
        cmdDeleteAnnotation2.setPreferredSize(new java.awt.Dimension(150, 32));
        cmdDeleteAnnotation2.setVerifyInputWhenFocusTarget(false);
        cmdDeleteAnnotation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteAnnotation2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        toolbar.add(cmdDeleteAnnotation2, gridBagConstraints);

        cmdImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-plus_32.png"))); // NOI18N
        cmdImport.setToolTipText("Delete this annotation");
        cmdImport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdImport.setIconTextGap(0);
        cmdImport.setMargin(new java.awt.Insets(2, 2, 2, 2));
        cmdImport.setMaximumSize(new java.awt.Dimension(32, 32));
        cmdImport.setMinimumSize(new java.awt.Dimension(32, 32));
        cmdImport.setPreferredSize(new java.awt.Dimension(32, 32));
        cmdImport.setVerifyInputWhenFocusTarget(false);
        cmdImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdImportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        toolbar.add(cmdImport, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(toolbar, gridBagConstraints);

        tabAnnotationContents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollPane.setViewportView(tabAnnotationContents);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 818;
        gridBagConstraints.ipady = 460;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(scrollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAnnotationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAnnotationsActionPerformed
        Object o = cmbAnnotations.getSelectedItem();
        if (o == null) {
            return;
        }

        if (o instanceof Annotation) {
            Annotation ann = (Annotation) o;

            tabAnnotationContents.setModel(new AnnotationTableModel(ann));
        }

    }//GEN-LAST:event_cmbAnnotationsActionPerformed

    private class AnnotationTableModel implements TableModel {

        Annotation ann;
        Dataset ds;

        public AnnotationTableModel(Annotation ann) {
            this.ann = ann;
            ds = ann.getBaseDataset();
        }
        ArrayList<TableModelListener> alTableModelListeners = null;

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            return String.class;
        }

        @Override
        public void addTableModelListener(TableModelListener l) {
            if (alTableModelListeners == null) {
                alTableModelListeners = new ArrayList<>();
            }
            alTableModelListeners.add(l);
        }

        @Override
        public int getColumnCount() {
            return 5;
        }

        private final String[] colNames = new String[]{"Event ID", "File Name", "Index in File", "Event Name", "Terms"};

        @Override
        public String getColumnName(int columnIndex) {
            return colNames[columnIndex];
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Datapoint d = ds.getDPByID(rowIndex);
            switch (columnIndex) {
                case 0:
                    return String.valueOf(d.getID());
                case 1:
                    return d.getFilename();
                case 2:
                    return d.getIndexInFile();
                case 3:
                    return d.getName();
                case 4:
                    return Arrays.toString(ann.getTermsForDpID(d.getID()));
                default:
                    throw new ArrayIndexOutOfBoundsException("Column index out of bounds: " + columnIndex);

            }
        }

        @Override
        public int getRowCount() {
            return ds.size();
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }

        @Override
        public void removeTableModelListener(TableModelListener l) {
            if (alTableModelListeners != null) {
                alTableModelListeners.remove(l);
            }
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
            return;
        }
    }

    private Annotation createNewAnnotation() {
        if (dataset == null) {
            return null;
        }
        JOptionPane.showMessageDialog(this, "Annotations can be imported from a file with the following format:\n<EventID> <tab-or-comma> <annotation term 1> <tab-or-comma> <annotation term 2>....\n\nEventIDs are unique identifiers of events (rows) in the dataset and can be obtained up by exporting any clustering as CSV - they will be written as the first column\nWhen ready, click 'OK' and select the file with your custom annotation");

        File f = IO.chooseFileWithDialog("ImportDatasetAnnotation", "CSV/Tab Delimited", new String[]{"csv", "txt"}, false);

        if (f != null) {
            try {
                StringBuilder sb = new StringBuilder();
                sb.append("Following rows were skipped. Do you want to proceed with import?\n");
                ArrayList<String> al = IO.getListOfStringsFromStream(new FileInputStream(f));
                ArrayList<String[]> alRows = new ArrayList<>();
                for (String s : al) {
                    String[] s2 = s.split("[,\t]");
                    if (s2.length < 2) {
                        sb.append("\nInvalid number of delimiters (must be at least 1): ");
                        sb.append(s);
                        continue;
                    }

                    try {
                        if (dataset.getDPByID(Integer.parseInt(s2[0])) == null) {
                            sb.append("\n This EventID has no matches in the given Dataset:");
                            sb.append(s);
                            continue;
                        }
                    } catch (NumberFormatException e) {
                        sb.append("\n Invalid numerical format of EventID:");
                        sb.append(s);
                        continue;
                    }catch (ArrayIndexOutOfBoundsException e) {
                        sb.append("\n EventID out of bounds:");
                        sb.append(s);
                        continue;
                    }
                    

                    alRows.add(s2);
                }
                boolean proceed = true;
                if (alRows.size() < al.size()) {
                    JScrollPane sp = new JScrollPane(new JTextArea(sb.toString()));
                    sp.setPreferredSize(new Dimension(500, 500));
                    sp.setMinimumSize(new Dimension(500, 500));
                    sp.setMaximumSize(new Dimension(500, 500));
                    proceed = JOptionPane.showConfirmDialog(this, sp, "Ready to import " + alRows.size() + " out of " + al.size() + "rows", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION;
                }
                if (proceed) {
                    String annName = "";
                    do {
                        annName = JOptionPane.showInputDialog(this, "Please specify the annotation name:");
                        for (Annotation ann : dataset.getAnnotations()) {
                            if (ann.getAnnotationName().equals(annName)) {
                                JOptionPane.showMessageDialog(this, "Annotation with this name already exists. Choose a different title", "Error", JOptionPane.ERROR_MESSAGE);
                                annName = "";
                                break;
                            }
                        }

                    } while (annName.isEmpty());
                    Annotation ann = new Annotation(dataset, annName);

                    HashMap<String, List<Integer>> hmProfileIDsForTerm = new HashMap<>();

                    for (String[] entry : alRows) {

                        String[] terms = Arrays.copyOfRange(entry, 1, entry.length);
                        Datapoint d = dataset.getDPByID(Integer.parseInt(entry[0]));

                        if (d == null || terms == null) {
                            continue;
                        }

                        // logger.print("dp, terms: " + d.getFullName() + ", " + Arrays.toString(terms));
                        for (String t : terms) {
                            if (hmProfileIDsForTerm.get(t) == null) {
                                hmProfileIDsForTerm.put(t, new LinkedList<>());
                            }
                            hmProfileIDsForTerm.get(t).add(d.getID());
                        }

                    }

                    for (String t : hmProfileIDsForTerm.keySet()) {
                        ann.addTerm(hmProfileIDsForTerm.get(t), t);
                    }

                    dataset.addAnnotation(ann);
                    return ann;
                }
            } catch (Exception e) {
                logger.showException(e);
            }
        }
        return null;
    }

    public void setDataset(Dataset nd) {
        Annotation[] annS = nd.getAnnotations();
        for (Annotation a : annS) {
            cmbAnnotations.addItem(a);
        }

    }

    private void cmdDeleteAnnotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteAnnotationActionPerformed
        Object o = cmbAnnotations.getSelectedItem();
        if (o instanceof Annotation) {
            if (((Annotation) o).getAnnotationName().startsWith("By file:")) {
                JOptionPane.showMessageDialog(this, "This annotation cannot be deleted");
                return;
            }

            dataset.removeAnnotation((Annotation) o);
            cmbAnnotations.setSelectedIndex(-1);
            cmbAnnotations.removeItem(o);
        }
        dtm = new DefaultTableModel(new String[]{"ProfileID", "Terms"}, 0);
        tabAnnotationContents.setModel(dtm);
    }//GEN-LAST:event_cmdDeleteAnnotationActionPerformed

    private void cmdDeleteAnnotation2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteAnnotation2ActionPerformed
        Object o = cmbAnnotations.getSelectedItem();
        if (o instanceof Annotation) {
            dlgRemapTerms frm = new dlgRemapTerms(frmMain.getInstance(), true, (Annotation) o);
            frm.setBounds(100, 100, frmMain.getInstance().getWidth() - 200, frmMain.getInstance().getHeight() - 200);
            frm.setVisible(true);
        }
        cmbAnnotations.setModel(new DefaultComboBoxModel(dataset.getAnnotations()));
    }//GEN-LAST:event_cmdDeleteAnnotation2ActionPerformed

    private void cmdImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdImportActionPerformed
        Annotation ann = createNewAnnotation();
        cmbAnnotations.setModel(new DefaultComboBoxModel(dataset.getAnnotations()));
        cmbAnnotations.setSelectedItem(ann);
    }//GEN-LAST:event_cmdImportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private samusik.glasscmp.GlassComboBox cmbAnnotations;
    private samusik.glasscmp.GlassButton cmdDeleteAnnotation;
    private samusik.glasscmp.GlassButton cmdDeleteAnnotation2;
    private samusik.glasscmp.GlassButton cmdImport;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tabAnnotationContents;
    private samusik.glasscmp.GlassToolBar toolbar;
    // End of variables declaration//GEN-END:variables
}
