/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KMeansParamPanel.java
 *
 * Created on 01-Dec-2009, 22:57:50
 */
package vortex.clustering;

/**
 *
 * @author Nikolay
 */
public class HierarchicalParamPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form KMeansParamPanel
     */
    public HierarchicalParamPanel() {
        initComponents();
    }

    public enum LinkageType {

        AverageLinkage, MinimalLinkage, CompleteLinkage, DivisiveMarkerTree
    }
    private LinkageType lt = LinkageType.AverageLinkage;

    public LinkageType getLinkageType() {
        return lt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        rbAvgLK = new javax.swing.JRadioButton();
        rbMinLK = new javax.swing.JRadioButton();
        rbMinLK1 = new javax.swing.JRadioButton();

        setMinimumSize(new java.awt.Dimension(300, 90));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(300, 90));
        setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Linkage type:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(jLabel2, gridBagConstraints);

        buttonGroup1.add(rbAvgLK);
        rbAvgLK.setSelected(true);
        rbAvgLK.setText("Average Linkage");
        rbAvgLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAvgLKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(rbAvgLK, gridBagConstraints);

        buttonGroup1.add(rbMinLK);
        rbMinLK.setText("Complete Linkage");
        rbMinLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMinLKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        add(rbMinLK, gridBagConstraints);

        buttonGroup1.add(rbMinLK1);
        rbMinLK1.setText("Minimal Linkage");
        rbMinLK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMinLK1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        add(rbMinLK1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void rbMinLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMinLKActionPerformed
        lt = LinkageType.MinimalLinkage;
    }//GEN-LAST:event_rbMinLKActionPerformed

    private void rbAvgLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAvgLKActionPerformed
        lt = LinkageType.AverageLinkage;
    }//GEN-LAST:event_rbAvgLKActionPerformed

    private void rbMinLK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMinLK1ActionPerformed
        lt = LinkageType.CompleteLinkage;
    }//GEN-LAST:event_rbMinLK1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbAvgLK;
    private javax.swing.JRadioButton rbMinLK;
    private javax.swing.JRadioButton rbMinLK1;
    // End of variables declaration//GEN-END:variables
}
